name: Hacktoberfest

on: [issues]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: ppb/pursuedpybear/.github/actions/hacktoberfest@action-hacktoberfest
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        label: new contributor
